# Generated by Django 5.1.2 on 2024-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
